version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Specify your Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip  # Upgrade pip to the latest version
      - pip install -r requirements.txt  # Install dependencies from requirements.txt

  pre_build:
    commands:
      - echo Running pre-build steps...

  build:
    commands:
      - echo Build started on `date`
      - python -m unittest discover  # Run tests (optional)

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'  # Include all files generated during the build

cache:
  paths:
    - '/root/.cache/pip'  # Cache pip dependencies
