version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify your Python version here
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # Install dependencies from requirements.txt
  pre_build:
    commands:
      - echo Pre-build phase
      - echo Running any pre-build commands...
      # Add any pre-build commands, such as linting or tests, if necessary
  build:
    commands:
      - echo Build phase
      - python app.py  # This is where your app runs or where you compile the project
  post_build:
    commands:
      - echo Post-build phase
      - echo Running any post-build commands...

artifacts:
  files:
    - '**/*'  # Include all files (adjust as needed)
  discard-paths: yes
